changelog:
  categories:
    - title: "Features"
      labels: ["enhancement","feat"]
    - title: "Bug Fixes"
      labels: ["bugfix","fix", "perf","bug"]
    - title: "Maintenance"
      labels: ["chore", "refactor", "style", "ci", "build"]
    - title: "Optimizations"
      labels: ["perf", "performance", "optimization"]
    - title: "Documentation"
      labels: ["docs", "documentation"]

  exclude:
    labels:
      - "ignore"
    authors:
      - "dependabot"