changelog:
  categories:
    - title: "Features"
      labels: ["enhancement","feat"]
    - title: "Bug Fixes"
      labels: ["bugfix","fix", "perf"]
    - title: "Maintenance"
      labels: ["chore", "refactor", "style"]
    - title: "Documentation"
      labels: ["docs"]

  exclude:
    labels:
      - "ignore"
    authors:
      - "dependabot"